import { readFileSync } from 'fs'
import { expect, test } from '@playwright/test'
import { docOf, expectTree, newMap, signUp, topic } from './helpers'

test.beforeEach(async ({ page }) => { await signUp(page) })

test('клавиши: Tab, Enter, Shift+Enter, правка, удаление, отмена', async ({ page }) => {
  const id = await newMap(page)
  await topic(page, 'Центральная тема').click()
  await page.keyboard.press('Tab')
  await page.keyboard.type('Альфа')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Enter')
  await page.keyboard.type('Гамма')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Shift+Enter')
  await page.keyboard.type('Бета')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Tab')
  await page.keyboard.type('Вложенная')
  await page.keyboard.press('Enter')
  await expectTree(page, id, 'Центральная тема[Альфа,Бета[Вложенная],Гамма]')
  await topic(page, 'Гамма').click()
  await page.keyboard.press('Delete')
  await page.keyboard.press('ControlOrMeta+z')
  await topic(page, 'Альфа').click()
  await page.keyboard.press('F2')
  await page.keyboard.press('ControlOrMeta+a')
  await page.keyboard.type('Альфа 2')
  await page.keyboard.press('Enter')
  await expectTree(page, id, 'Центральная тема[Альфа 2,Бета[Вложенная],Гамма]')
})

test('перетаскивание меняет родителя', async ({ page }) => {
  const id = await newMap(page, { version: 1, sheets: [{ id: 's', title: 'Л', rootTopic: { id: 'r', title: 'Корень', children: [
    { id: 'a', title: 'Первая', children: [{ id: 'a1', title: 'Лист' }] }, { id: 'b', title: 'Вторая', children: [] }] } }] })
  const from = await topic(page, 'Лист').boundingBox()
  const to = await topic(page, 'Вторая').boundingBox()
  await page.mouse.move(from!.x + from!.width / 2, from!.y + from!.height / 2)
  await page.mouse.down()
  await page.mouse.move(to!.x + to!.width / 2, to!.y + to!.height / 2, { steps: 8 })
  await page.mouse.up()
  await expectTree(page, id, 'Корень[Первая,Вторая[Лист]]')
})

test('раскладки и стиль через панель формата', async ({ page }) => {
  const id = await newMap(page)
  await topic(page, 'Центральная тема').click()
  await page.getByLabel('Формат', { exact: true }).click()
  await page.getByTestId('format-panel').locator('select[aria-label="Структура"]').selectOption('org-down')
  await page.getByRole('button', { name: 'Карта', exact: true }).last().click()
  await page.getByRole('button', { name: 'Цветовая тема', exact: true }).click()
  await page.getByRole('button', { name: 'Цветовая тема Космос' }).click()
  await page.getByRole('switch', { name: 'Цветные ветки' }).last().click()
  await expect.poll(async () => (await docOf(page, id)).sheets[0], { timeout: 10_000 })
    .toMatchObject({ structure: 'org-down', palette: 'space', rainbow: false })
  await expect(page.getByTestId('map-canvas')).toHaveCSS('background-color', 'rgb(13, 47, 66)')
})

test('структура (outliner) и поиск', async ({ page }) => {
  const id = await newMap(page)
  await page.locator('.mode-btn').click()
  const root = page.getByTestId('outliner').locator('textarea').first()
  await root.click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.type('Пункт')
  await page.keyboard.press('Enter')
  await page.keyboard.type('Подпункт')
  await page.keyboard.press('Tab')
  await page.locator('body').click({ position: { x: 5, y: 890 } })
  await expectTree(page, id, 'Центральная тема[Пункт[Подпункт]]')
  await page.locator('.mode-btn').click()
  await page.keyboard.press('ControlOrMeta+f')
  await page.getByPlaceholder('Поиск по темам, заметкам и меткам').fill('пункт')
  await expect(page.getByTestId('search-bar')).toContainText('1 из 2')
})

test('экспорт и импорт .xmind через меню', async ({ page }) => {
  await newMap(page, { version: 1, sheets: [{ id: 's', title: 'Л', rootTopic: { id: 'r', title: 'Экспорт', children: [{ id: 'a', title: 'Ветка', markers: ['priority-1'] }] } }] })
  await page.getByRole('button', { name: 'Меню' }).click()
  await page.getByRole('menuitem', { name: 'Экспортировать как' }).hover()
  const dl = page.waitForEvent('download')
  await page.getByRole('menuitem', { name: 'XMind', exact: true }).click()
  const file = await (await dl).path()
  await page.getByRole('button', { name: 'Меню' }).click()
  await page.getByRole('menuitem', { name: 'Файл', exact: true }).hover()
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('menuitem', { name: 'Импорт файла' }).click()
  await (await chooser).setFiles({ name: 'копия.xmind', mimeType: 'application/zip', buffer: readFileSync(file!) })
  await expect(page.locator('.title-input')).toHaveValue('копия')
  await expect(topic(page, 'Ветка').locator('[data-marker="priority-1"]')).toBeVisible()
})

test('комментарии: метка на карте, ответ, «решено»', async ({ page }) => {
  const id = await newMap(page)
  await page.getByRole('button', { name: 'Комментарии', exact: true }).click()
  await page.getByTestId('comments-panel').getByRole('button', { name: 'Добавить комментарий' }).last().click()
  await topic(page, 'Центральная тема').click()
  await page.getByLabel('Текст комментария').fill('Первый')
  await page.getByLabel('Отправить').click()
  await expect(page.getByTestId('comment-pin')).toHaveText('1')
  await page.getByLabel('Текст комментария').fill('Ответ')
  await page.keyboard.press('ControlOrMeta+Enter')
  await expect(page.getByTestId('comment-pin')).toHaveText('2')
  await expect.poll(async () => (await docOf(page, id)).sheets[0].rootTopic.comments?.map((c: { text: string }) => c.text)).toEqual(['Первый', 'Ответ'])
  await page.getByRole('dialog', { name: 'Обсуждение' }).getByLabel('Решено').click()
  await expect(page.getByTestId('comment-pin')).toHaveCount(0)
  await expect(page.getByText('Нет подходящих комментариев')).toBeVisible()
})

test('презентация: слайды и шаги', async ({ page }) => {
  await newMap(page)
  await topic(page, 'Центральная тема').click()
  await page.keyboard.press('Tab'); await page.keyboard.type('Первая'); await page.keyboard.press('Enter')
  await page.keyboard.press('Enter'); await page.keyboard.type('Вторая'); await page.keyboard.press('Enter')
  await page.getByLabel('Презентация', { exact: true }).click()
  const stage = page.locator('.pitch-stage')
  await expect(stage).toContainText('Центральная тема')
  await page.keyboard.press('ArrowRight')
  await expect(stage).toHaveAttribute('data-slide', '2')
  await page.keyboard.press('ArrowRight')
  await expect(stage).toContainText('Первая')
  await expect(stage).not.toContainText('Вторая')
  await page.keyboard.press('ArrowRight')
  await expect(stage).toContainText('Вторая')
  await page.keyboard.press('ArrowRight')
  await expect(stage).toHaveAttribute('data-slide', '3')
  await page.getByLabel('Выйти из презентации').click()
  await expect(page.getByTestId('presentation')).toHaveCount(0)
})

test('задача: панель слева, карточка в теме, диаграмма Ганта', async ({ page }) => {
  const id = await newMap(page)
  await topic(page, 'Центральная тема').click()
  await page.getByLabel('Вставить', { exact: true }).click()
  await page.getByRole('menuitem', { name: 'Задача' }).click()
  const panel = page.getByTestId('task-panel')
  await expect(panel).toBeVisible()
  await panel.getByLabel('Начало').fill('2026-10-10')
  await panel.getByLabel('Длительность').fill('3')
  await panel.getByLabel('Прогресс').selectOption('50')
  await expect.poll(async () => (await docOf(page, id)).sheets[0].rootTopic.taskInfo).toMatchObject({ start: '2026-10-10', end: '2026-10-12', progress: 50 })
  await expect(page.locator('.topic-task')).toContainText('3 дня')
  await page.getByLabel('Гант', { exact: true }).click()
  const g = page.getByTestId('gantt')
  await expect(g.locator('.gt-row:not(.head)')).toHaveCount(1)
  await expect(g.locator('.gc-bar')).toHaveCount(1)
  await panel.getByRole('switch', { name: 'Показывать в теме' }).click()
  await expect(page.locator('.topic-task')).toHaveCount(0)
  await panel.getByRole('button', { name: 'Удалить' }).click()
  await expect(g.locator('.gc-bar')).toHaveCount(0)
  await expect(panel).toContainText('В этой теме нет задачи')
  await panel.getByRole('button', { name: 'Вставить' }).click()
  await expect(g.locator('.gt-row:not(.head)')).toHaveCount(1)
})
