import { readFileSync } from 'fs'
import { expect, test } from '@playwright/test'
import { docOf, newMap, signUp, titles, topic } from './helpers'

test.beforeEach(async ({ page }) => { await signUp(page) })

test('клавиши: Tab, Enter, Shift+Enter, правка, удаление, отмена', async ({ page }) => {
  const id = await newMap(page)
  await topic(page, 'Центральная тема').click()
  await page.keyboard.press('Tab')
  await page.keyboard.type('Альфа')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Enter')
  await page.keyboard.type('Гамма')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Shift+Enter')
  await page.keyboard.type('Бета')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Tab')
  await page.keyboard.type('Вложенная')
  await page.keyboard.press('Enter')
  let d = await docOf(page, id)
  expect(titles(d.sheets[0].rootTopic)).toBe('Центральная тема[Альфа,Бета[Вложенная],Гамма]')
  await topic(page, 'Гамма').click()
  await page.keyboard.press('Delete')
  await page.keyboard.press('ControlOrMeta+z')
  await topic(page, 'Альфа').click()
  await page.keyboard.press('F2')
  await page.keyboard.press('ControlOrMeta+a')
  await page.keyboard.type('Альфа 2')
  await page.keyboard.press('Enter')
  d = await docOf(page, id)
  expect(titles(d.sheets[0].rootTopic)).toBe('Центральная тема[Альфа 2,Бета[Вложенная],Гамма]')
})

test('перетаскивание меняет родителя', async ({ page }) => {
  const id = await newMap(page, { version: 1, sheets: [{ id: 's', title: 'Л', rootTopic: { id: 'r', title: 'Корень', children: [
    { id: 'a', title: 'Первая', children: [{ id: 'a1', title: 'Лист' }] }, { id: 'b', title: 'Вторая', children: [] }] } }] })
  const from = await topic(page, 'Лист').boundingBox()
  const to = await topic(page, 'Вторая').boundingBox()
  await page.mouse.move(from!.x + from!.width / 2, from!.y + from!.height / 2)
  await page.mouse.down()
  await page.mouse.move(to!.x + to!.width / 2, to!.y + to!.height / 2, { steps: 8 })
  await page.mouse.up()
  const d = await docOf(page, id)
  expect(titles(d.sheets[0].rootTopic)).toBe('Корень[Первая,Вторая[Лист]]')
})

test('раскладки и стиль через панель формата', async ({ page }) => {
  const id = await newMap(page)
  await topic(page, 'Центральная тема').click()
  await page.getByLabel('Структура').selectOption('org-down')
  await page.getByRole('button', { name: 'Карта', exact: true }).last().click()
  await page.locator('.theme-card', { hasText: 'Тёмная' }).click()
  await page.getByLabel('Радужные ветки').check()
  const d = await docOf(page, id)
  expect(d.sheets[0]).toMatchObject({ structure: 'org-down', theme: 'dark', rainbow: true })
})

test('структура (outliner) и поиск', async ({ page }) => {
  const id = await newMap(page)
  await page.getByRole('button', { name: 'Структура' }).click()
  const root = page.getByTestId('outliner').locator('textarea').first()
  await root.click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.type('Пункт')
  await page.keyboard.press('Enter')
  await page.keyboard.type('Подпункт')
  await page.keyboard.press('Tab')
  await page.locator('body').click({ position: { x: 5, y: 890 } })
  const d = await docOf(page, id)
  expect(titles(d.sheets[0].rootTopic)).toBe('Центральная тема[Пункт[Подпункт]]')
  await page.getByRole('button', { name: 'Карта', exact: true }).first().click()
  await page.keyboard.press('ControlOrMeta+f')
  await page.getByPlaceholder('Поиск по темам, заметкам и меткам').fill('пункт')
  await expect(page.getByTestId('search-bar')).toContainText('1 из 2')
})

test('экспорт и импорт .xmind через меню', async ({ page }) => {
  await newMap(page, { version: 1, sheets: [{ id: 's', title: 'Л', rootTopic: { id: 'r', title: 'Экспорт', children: [{ id: 'a', title: 'Ветка', markers: ['priority-1'] }] } }] })
  await page.getByRole('button', { name: 'Файл ▾' }).click()
  const dl = page.waitForEvent('download')
  await page.getByRole('menuitem', { name: 'XMind (.xmind)' }).click()
  const file = await (await dl).path()
  await page.getByRole('button', { name: 'Файл ▾' }).click()
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('menuitem', { name: /Открыть файл/ }).click()
  await (await chooser).setFiles({ name: 'копия.xmind', mimeType: 'application/zip', buffer: readFileSync(file!) })
  await expect(page.locator('.title-input')).toHaveValue('копия')
  await expect(topic(page, 'Ветка').locator('[data-marker="priority-1"]')).toBeVisible()
})
